{
  const {vars, toCall, toMCall, reduce, map, clearVars} = P.getHelpers({error});
  clearVars();
}

start
  = s:statements _ {return {root: {type: 'program', statements: s}};}

statements
  = s:statement _ ss:statements {return [s, ...ss];}
  / s:statement {return [s];}

statement
  = _ c:fme _ ";" {return c;}
  / _ "const" _ x:identifier2 _ "=" _ c:arg _ ";"
  {
    const newC = {
      type: 'const',
      name: x.text,
      location: x.location,
      value: c,
      readOnly: true,
    };

    vars[x.text] = newC;

    return newC;
  }
  / letStatement
  / assignment
  / ifStatement

letStatement
  = _ LET _ x:identifier2 _ "=" _ v:number _ ";"
  {
    const newC = {
      type: 'const',
      name: x.text,
      location: x.location,
      value: v,
      readOnly: false,
    };

    vars[x.text] = newC;

    return {
      type: 'let',
      name: x,
      value: v,
      readOnly: true,
    };
  }

assignment
  = x:identifier2 _ "=" _ v:number _ ";"
  {
    const ref = vars[x.text];
    if (!ref) {
      error(`Unknown identifier ${x.text}`);
    }

    if (ref.readOnly) {
      error(`Cannot assign to ${x.text} defined as const.`);
    }

    return {
      type: 'assign',
      name: x,
      value: v,
    };
  }

ifStatement
  = _ IF _ "(" _ b:boolExpression _ ")" _ "{" _ s:statements _ "}"
  {
    return {
      type: 'condition',
      condition: b,
      statements: s
    };
  }

args
  = a:arg _ "," _ as:args {return [a, ...as];}
  / a:arg {return [a];}

arg
  = f:fme {return {...f, location: location()};}
  / n:number {return {type: 'literal', name: 'number', value: n, location: location()};}
  / t:timePattern {return {type: 'timePattern', name: 'timePattern', value: t, location: location()}}
  / a:literal {return {type: 'literal', value: a, location: location()};}
  / h:handler {return {type: 'handler', ...h, location: location()};}

handler
  = "(" a:inputArgs? ")" _ "=>" _ s:handlerBody
  {
    return {argNames: a || [], body: s};
  }

handlerBody
  = "{" _ s:statements _ "}" {return s;}
  / s:fme {return [s];}

inputArgs
  = a:identifier _ "," _ as:inputArgs {return [a, ...as];}
  / a:identifier {return [a];}

fme
  = x:memberExpression
  {
    return reduce(
      (p, c) => console.log('fme', p) ||
        [{type: 'call', name: c.name, args: [...(c.args || []), ...toMCall(p)], location: c.location}],
        [],
        x)[0];
    }

memberExpression
  = i:f _ "." _ e:memberExpression { return [i, ...e]; }
  / i:f {return [i];}

boolExpression
  = left:(fme / number) _ boolOperator _ right:(fme / number) {return {left, right, location: location()}}
  / fme

boolOperator
  = ">" / "<" / "=="

f
  = i:identifier _ "(" _ a:args? _ ")" {return toCall(i, a, location(), 'a');}
  / i:identifier !("(") {return toCall(i, [], location(), 'b');}

identifier "Identifier"
  = !(keywords / [0-9] ) x:namechar+ {return x.join('');}

identifier2 "Identifier"
  = !(keywords / [0-9] ) x:namechar+ {return {text: x.join(''), location: location()};}

literal "Literal"
  = "'" s:([^\']*) "'"
  {
    return s.join('');
  }

keywords
  = IF / CONST / LET

IF
  = "if"i

CONST
  = "const"i

LET
  = "let"i

/* TIME PATTERN */

timePattern
  = '"' p:(unquotedTimePattern) '"' {return p;}

unquotedTimePattern
  = randomizedTime {return text()}
  / absoluteTime {return text()}
  / timeInterval {return text()}

absoluteTime
  = datePart timePart

randomizedTime
  = absoluteTime aTimePart

timeInterval
  = timePart "/" timePart

datePart
  = digit4 "-" digit2 "-" digit2

timePart
  = "T" hms

aTimePart
  = "A" hms

hms
  = H ":" M ":" S

H "Hours"
  = digit2

M "Minutes"
  = digit2

S "Seconds"
  = digit2

digit2
  = digit digit

digit3
  = digit digit digit

digit4
  = digit digit digit digit

digit
  = [0-9]

/* TIME PATTERN END*/

namechar
  = [a-zA-Z0-9_$]

number "Number"
  = n:([0-9]+) {return parseInt(n.join(''), 10);}

_ "whitespace"
  = [ \t\n\r]*

//handle(button1(dim(1)), 'sdf', () => { group(7).on; });
