{
  let refId = 0;
  const sensors = {};
  const groups = {};
  const rules = [];
  const schedules = [];
  const isDefined = id => sensors[id] || groups[id];
  const getType = id => sensors[id] ? sensors[id].type : groups[id] ? 'group' : 'undefined';
  const eventNames = {
    dimmer: ['initial_press', 'repeat', 'short_release', 'long_release'],
  };
  const typeMethods = {
    'undefined': [],
    'group': ['setScene', 'alert', 'on', 'off'],
    'dimmer': [],
    'status': ['set'],
  };
  const buttonNames = {
    dimmer: ['button1', 'button2', 'button3', 'button4'],
  };
  const eventCodes = {
    dimmer: {
      button1: {
        initial_press: 1000,
        repeat: 1001,
        short_release: 1002,
        long_release: 1003,
      },
      button2: {
        initial_press: 2000,
        repeat: 2001,
        short_release: 2002,
        long_release: 2003,
      },
      button3: {
        initial_press: 3000,
        repeat: 3001,
        short_release: 3002,
        long_release: 3003,
      },
      button4: {
        initial_press: 4000,
        repeat: 4001,
        short_release: 4002,
        long_release: 4003,
      }
    }
  };

  const getRef = () => refId++;

  const actionTranslate = action => {
    if (action.member) {
      if (!isDefined(action.member)) {
        error(`${action.member} is not defined.`);
      }
      const type = getType(action.member);
      if (!typeMethods[type].includes(action.name)) {
        error(`${action.member} has no ${action.name} method. Available methods: ${typeMethods[type].join(', ')}`);
      }
    }

    if (action.type === 'methodCall' && !action.member && action.name === 'setTimeout') {
      const scheduleRef = getRef();

      schedules.push({ref: scheduleRef, def:{
        name: "hs:schedule",
        "command": actionTranslate(action.args[0].value[0]),
        "localtime": `PT${new Date(action.args[1].value * 1000).toISOString().substr(11, 8)}`,
        "autodelete": false,
        "status": "disabled"
      }});

      return {
        "address": `ref(${scheduleRef})`,
        "method": "PUT",
        "body": {
          "status": "enabled"
        }
      };
    } else if (action.type === 'methodCall' && action.member && action.name === 'on') {
      const group = groups[action.member];
      return {
        "address": `/groups/${group.id}/action`,
        "method": "PUT",
        "body": {
          "on": true,
        }
      };
    } else if (action.type === 'methodCall' && action.member && action.name === 'off') {
      const group = groups[action.member];
      return {
        "address": `/groups/${group.id}/action`,
        "method": "PUT",
        "body": {
          "on": false,
        }
      };
    } else if (action.type === 'methodCall' && action.member && action.name === 'alert') {
      const group = groups[action.member];
      return {
        "address": `/groups/${group.id}/action`,
        "method": "PUT",
        "body": {
          "alert": "select",
        }
      };
    }
  };

  const process = (actions, baseConditions, name) => {
    const finalActions = [];
    const conditions = [...baseConditions];

    for (let i = 0; i < actions.length; i++) {
      const action = actions[i];

      finalActions.push(actionTranslate(action));
    }

    rules.push({
      name: name.substr(0, 32),
      conditions,
      actions: finalActions
    });
  };
}

statements
  = s:(statement / comment)*
  {
    console.log('s', s);
    return {schedules, rules};
  }

statement
  = x:(constDef / eventHandlerAttach) _ ";" _
  { return x;}

constDef
  = "const" _ i:identifier _ "=" _ o:constructor
  {
    if (o.type === 'dimmer' || o.type === 'status') {
      sensors[i] = o;
    } else if (o.type === 'group') {
      groups[i] = o;
    }
    return {
      type: 'ref',
      objType: o.type,
      name: i,
      value: o,
    };
  }

constructor
  = i:identifier _ "(" _ n:number _ ")"
  {
    if (!['dimmer', 'group', 'status'].includes(i)) {
      error(`unknown constructor ${i}`);
    }
    return {type: i, id: n};
  }

eventHandlerAttach
  = s:identifier _ "." _ b:identifier _ "." _ "on" _ "(" _ e:literal _ "," _
    h:eventHandler _ ")"
  {
    if (!isDefined(s)) {
      error(`${s} is not defined.`);
    }

    const sensor = sensors[s];

    if (!sensor) {
      error(`${s} has no field ${b}`);
    }

    if (!buttonNames[sensor.type].includes(b)) {
      error(`${s} has no button named ${b}. Available buttons: ${buttonNames[sensor.type].join(', ')}`);
    }

    if (!eventNames[sensor.type].includes(e)) {
      error(`${s} has no event named ${e}. Available events: ${eventNames[sensor.type].join(', ')}`);
    }

    const baseConditions = [
    {
      "address": `/sensors/${sensor.id}/state/buttonevent`,
      "operator": "eq",
      "value": '' + eventCodes[sensor.type][b][e]
    },
    {
      "address": `/sensors/${sensor.id}/state/lastupdated`,
      "operator": "dx"
    }
    ];

    process(h, baseConditions, `hs:${s} ${b} ${e}`);

    const outerActions = h.filter(x => !x.condition);


/*
    if (outerActions.length > 0) {
      rules.push({
          name: `hs:${s} ${b} ${e}`.substr(0, 32),
          conditions: baseConditions,
          actions: outerActions
      });
    }

    for (let i = 0; i < h.length; i++) {
        const conditions = [...baseConditions];

        if (h[i].condition) {
          conditions.push(h[i].condition);

          rules.push({
            name: `hs:${s} ${b} ${e} ${i}`.substr(0, 32),
            conditions,
            actions: h[i].condition ? h[i].actions : h[i]
          });
        }
    }
*/
    return {
      type: 'event',
      eventType: `${b}.${e}`,
      source: s,
      actions: h,
    };
  }

identifier "Identifier"
  = i:([a-zA-Z0-9]+) {return i.join('');}

literal "Literal"
  = "'" s:([^\']+) "'"
  {
    return s.join('');
  }

eventHandler "Lambda Expression"
  = "(" _ ")" _ "=>" _ "{" _ a:actions _ "}"
  {
    return a;
  }

actions
  = action*

action
  = a:(condition / methodCall) {return a;}

condition
  = "if" _ "(" _ e:compareExpression _ ")" _ "{" _ a:actions _ "}" _
  {
    return {
      type: 'condition',
      condition: e,
      actions: a
    };
  }

compareExpression
  = i:identifier _ o:operator _ n:number
  {
    const v = sensors[i];

    return {
      "address": `/sensors/${v.id}/state/status`,
      "operator": o,
      "value": '' + n
    };
  }

operator
  = "==" {return 'eq';}
  / "<" {return 'lt';}

arg
  = l:literal { return {type: 'literal', value: l};}
  / n:number { return {type: 'number', value: n};}
  / a:eventHandler { return {type: 'lambda', value: a};}

argList
  = a:arg _ "," _ as:argList {return [a, ...as]} / a:arg {return [a]} / _ {return []}

member
  = x:identifier _ "." {return x;}

methodCall
  = x:member? _ m:identifier _ "(" _ args:argList _ ")" _ ";" _
  {
    return {
      type: 'methodCall',
      member: x,
      name: m,
      args
    };
  }

number "Number"
  = n:([0-9]+) {return parseInt(n.join(''), 10);}

comment
  = "//" p:([^\n]*) _
  {
    return {
      type: 'comment',
      value: p.join('')
    };
  }

_ "whitespace"
  = [ \t\n\r]*
/*

a.b.c('d');
c(b(a()), 'd')

*/
